graph TD
    rect[Rectangle Label]
    round(Rounded Label)
    circle((Circle Label))
    diamond{Decision Label}
    hex{{Hexagon Label}}
    stadium([Stadium Label])
    cylinder[(Cylinder Label)]
    subroutine[[Subroutine Label]]

    rect --> round
    round --> circle
    circle --> diamond
    diamond --> hex
    hex --> stadium
    stadium --> cylinder
    cylinder --> subroutine
